music_directory "/mnt/hdd/music"
audio_output {
    type "pulse"
    name "Pipewire Output"
}
port                    "6600"
playlist_directory      "~/.mpd/playlists"
db_file                 "~/.mpd/mpd.db"
log_file                "~/.mpd/mpd.log" 
state_file              "~/.mpd/mpdstate"
